[tool.black]
line-length = 120
target-version = ['py37']

[tool.isort]
line_length = 120
multi_line_output = 3
force_alphabetical_sort_within_sections = "True"
force_sort_within_sections = "False"
known_richclick = ["rich_click"]
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
    "RICHCLICK",
]
profile = "black"

[tool.mypy]
python_version = "3.8"
scripts_are_modules = "True"
strict = "True"

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "sdist",
    "tests/**",
    "examples/**",
]
ignore = [
    "D100",
    "D102",
    "D205",
    "E731",
    "D203",
    "D212"
]
line-length = 120
select = [
    "D",
    "E",
    "F",
    "W",
    "I001"
]

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["rich-click"]

[tool.pyright]
include = ["src"]
pythonVersion = "3.7"
typeCheckingMode = "basic"
executionEnvironments = [
    { root = "src" },
    { root = "tests", extra_paths = [
        "src",
    ] },
]

[tool.pytest.ini_options]
addopts = "-s -rP -vv --showlocals"
pythonpath = ["tests", "src"]
testpaths = ["tests"]
